### PR TITLE
Interfaces. Unit test example

### PR DESCRIPTION
**Pull request by smikis**
I extracted web client so separate class so it's possible to mock returned data. It's still not ideal, and ApiReader should probably get updated too, but it should work for now

### CODE REVIEW

**Comment by avivbiton** [comment]
Is the interface for the diablo api really necessary? it kinda looks over the top and I feel like there is nothing much the mock here.  
About the tests, it said tests shouldn't relay on a remote api call, then we shouldn't really include calling the actual blizzard api in the tests only maybe just mock a response instead.
Beside that it looks good.

**Comment by avivbiton** [comment]
Which the new changes @linahanner made, can you maybe just copy the unit tests and the changes you made since there are some conflicting files at the moment.

**Comment by smikis** [comment]
Sure, I'll solve conflicts tomorrow and look if changes are still necessary

**Comment by avivbiton** [comment]
Since this is getting old, I will close this for now, When you have time, we'd be happy to have you continue to contribute to the library @smikis

**Pull request closed without merging**
